version: '3'
services:
  composer:
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app
  php:
    image: php:8.2-cli
    volumes:
      - ./:/app
    working_dir: /app
    command: ["php", "console.php"]
